### ISSUE TITLE
Support keyboard arrow keys?

### ISSUE THREAD

**Issue by level323** [garybernhardt/selecta#100]
Hi,

I found your awesome tool accidentally via [this reddit thread](https://www.reddit.com/r/Python/comments/5tiyry/do_you_maintain_a_python_librarytool_that_you/).

However, I was wondering if you'd be willing to contemplate supporting up/down arrow keyboard keys in addition to Ctrl+N/P? At the very least, perhaps consider making changes so that arrow keypresses don't cause `selecta` to exit?

If you are open to accepting a PR to add this feature, I would be willing to have a go at making the changes but my Ruby-fu is relatively weak.

**Comment by garybernhardt** [comment]
Sorry, but it's not likely. This has been discussed in many issues, including #15, #36, #48, and #76. Please search for past issues before opening new ones.

**Comment by level323** [comment]
My bad!
