### ISSUE TITLE
Respecting gitignore?

### ISSUE THREAD

**Issue by shelldandy** [garybernhardt/selecta#102]
Is there a way to use as fuzzy file finder in vim respecting gitignores?? :O

**Comment by rschmitt** [comment]
Why not pipe it the input from `rg --files`? (see [ripgrep](https://github.com/BurntSushi/ripgrep) for the `rg` command)

**Comment by srstevenson** [comment]
@shelldandy You might be interested in [vim-picker](https://github.com/srstevenson/vim-picker), which can use `selecta` and respects `.gitignore` files.

**Comment by shelldandy** [comment]
thanks for both great amazing options guys!

**Comment by garybernhardt** [comment]
Seconded: thanks for those recommendations. I'd never seen vim-picker before. That seems like a nice way to provide the vim integration for fuzzy text selectors!
