### ISSUE TITLE
Alternative to Ctr-c

### ISSUE THREAD

**Issue by RobertAudi** [garybernhardt/selecta#49]
At the moment, if I want to get out the selecta prompt (essantially cancelling the search), I have to press `Ctrl-c`. That is often tedious. It would be better is I could get out of selecta by pressing `Esc`, or even `Enter` when no search query has been entered; That assumes that no search result is pre-selected.

**Comment by garybernhardt** [comment]
I've reverted ESC support in 2db9e660233447deb32501ffa81d19bf27525b63 due to the problem described in #71.

**Comment by alexch** [comment]
eek! yeah, that's unfortunate...  If I start to use selecta again and put ESC back with a small delay like you suggested, would you accept a patch?

**Comment by untitaker** [comment]
Maybe it's such an obviously silly idea, but still, I didn't get any response in #71:

What about simply requiring ESC to be hit twice? This would make ``?\C-[`` a prefix of both the arrow keys and the double-ESC, allowing selecta to distinguish between those without implementing a timeout. Whether this is worth the UI weirdness I don't know (depends on how easy it is to implement the timeout hack)

**Comment by garybernhardt** [comment]
@alexch @untitaker I really don't want to debug and maintain any kind of input state machine. I suspect that even something this simple wouldn't be portable. We once tried to add arrow key support, and that didn't even work across different Macs running OS X.
