### ISSUE TITLE
Optimize matching

### ISSUE THREAD

**Issue by ggilder** [garybernhardt/selecta#53]
Just opening this as a reminder from https://github.com/garybernhardt/selecta/pull/51. I started to look at rebasing my commit but then I figured if the algorithm is changing a lot it will end up being unusable anyway.

So for the future, the two performance improvements I implemented in https://github.com/garybernhardt/selecta/commit/f695810129a810517adf37212f2400bd1a389b17 were:
- Don't re-score eliminated choices when appending to query — effectively, `Search` would maintain a list of "choices" and "candidates" — candidates being choices that match the query. When appending to a query, `Search` would pass along the existing list of candidates so that the new query can be run over a smaller list.
- Cache previously calculated character indexes on choices — this may not apply depending on changes to the scoring algorithm, but basically calculate and cache character indexes on each choice (in my commit, done by introducing a new `Choice` object) so that they don't have to be recalculated on each pass. Not sure how this could be incorporated while keeping the "functional core" concept, however.

**Comment by garybernhardt** [comment]
This is outdated as of the merge of new perf/scoring code in d874c99dd7f0f94225a95da06fc487b0fa5b9edc.
