### ISSUE TITLE
Keyboard input issues after integrating with Vim 7.4.430?

### ISSUE THREAD

**Issue by wiegand** [garybernhardt/selecta#56]
Using Selecta with Vim is buggy for me after upgrading to Vim `7.4.430`, though I don't have enough information to rule out a coincidence.
## Behavior
- Keyboard input is now extremely sluggish. The display often takes near a second to sync.
- All control-keys with the exception of `^C` have stopped working, i.e. they do nothing.
- Pressing the backspace key also does nothing.
## Setup

I am integrating Selecta with Vim as suggested in the README:

``` VimL
function! SelectaCommand(choice_command, selecta_args, vim_command)
  try
    silent let selection = system(a:choice_command . " | selecta " . a:selecta_args)
  catch /Vim:Interrupt/
    " Swallow the ^C so that the redraw below happens; otherwise there will be
    " leftovers from selecta on the screen
    redraw!
    return
  endtry
  redraw!
  exec a:vim_command . " " . selection
endfunction

nnoremap <leader>p :call SelectaCommand("find * -type f", "", ":e")<cr>
```
### Selecta

I am running [`8179c87`.](https://github.com/garybernhardt/selecta/commit/8179c87d10ca951ab287e694f48b7723102e535f)
### Vim

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep  2 2014 09:11:05)
MacOS X (unix) version
Included patches: 1-430
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.9 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/Users/user/.rbenv/versions/2.1.2/lib  -fstack-protector -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector -L/usr/local/lib  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby-static -framework CoreFoundation -lgmp -lobjc -L/Users/user/.rbenv/versions/2.1.2/lib
```

I am running OS X 10.9.4.

**Comment by rschmitt** [comment]
Yup, this has something to do with patch 427 https://github.com/b4winckler/vim/commit/f9d38e5ad8416f1bd1d3a48ed16971ae1195b147. I've learned a few interesting things about this bug:

1. Control keys don't exactly stop working, but rather they're somehow intercepted by the terminal driver. For instance, ^T reports the status line (cf. `kerninfo` in the `stty` man page).
2. You can actually pass control keys through by prefixing them with ^V, the `lnext` control character, which interprets the next keystroke literally. So ^U won't do anything, but ^V^U will clear the query.
3. This seems to have nothing to do with stty itself. Even when invoking stty with a known good `stty -g` configuration from an older version of vim, the bug persists. It's incredibly stubborn.
4. Disabling echoing of the query does nothing. (I'm not referring to `stty echo`, but rather the actual printing of the query as part of the prompt line.)
5. Disabling threading/buffering does nothing.

This bug also reminds me a bit of https://github.com/neovim/neovim/issues/1044. It seems like vim continues to read from the terminal, or at least fight over keystrokes with Selecta, when COOKED mode is set. But that's merely a vague intuition. This is a seriously abstruse problem, even by terminal standards. And I've reproduced it on both OS X _and_ Ubuntu!

**Comment by rschmitt** [comment]
Just for reference, here's a severely long article I just found which might contain some clues. http://www.linusakesson.net/programming/tty/

**Comment by garybernhardt** [comment]
@rschmitt, does the bug still sometimes happen with `silent` removed, or are you digging into it on principle, to really figure out what's going on?

**Comment by rschmitt** [comment]
I just started using that workaround, but I expect it to continue working. (I've also found at least one version of Selecta that works even with `silent`, but I haven't had a chance to investigate why.) I'm digging into this out of principle, and because I suspect that this same bug will show up in some other context. If I ever find the root cause, I'll be sure to write up my findings. I personally suspect that it has something to do with the process and job control model, and/or the use of `stty` (as opposed to invoking `tcsetattr` directly).

**Comment by rschmitt** [comment]
I figured it out. Vim shells out to run an external command by calling [`mch_call_shell`](https://github.com/b4winckler/vim/blob/master/src/os_unix.c#L3584-L3597), which actually busywaits for the child process to finish. This is done in [`wait4pid`](https://github.com/b4winckler/vim/blob/master/src/os_unix.c#L3584-L3597) (note the use of `WNOHANG`), which calls [`mch_delay`](https://github.com/b4winckler/vim/blob/master/src/os_unix.c#L608), and _that_ function screws with the terminal mode. Specifically, _if the terminal is in raw mode_ (which, as of patch #427, is the case when `silent` is used), it [will be set](https://github.com/b4winckler/vim/blob/master/src/os_unix.c#L619-L625) to `TMODE_SLEEP`, which is cooked mode without echo. So when Selecta is running with `silent`, vim is performing the following sequence in a continuous loop:

1. Switch to cooked mode without echo
2. Sleep for ten milliseconds
3. Switch back to raw mode

Another weird consequence of this (which can be seen by attaching `strace` or running vim from a `script(1)` session and then firing up Selecta) is that vim will emit a continuous stream of [exotic xterm control sequences](https://github.com/b4winckler/vim/blob/master/src/os_unix.c#L3584-L3597) to the terminal to repeatedly enable and disable mouse support.

**Comment by garybernhardt** [comment]
This is both fascinating and an extremely impressive feat of diagnosis! Do you think that the vim maintainers would consider this a bug? It certainly violates my expectations: once Vim has shelled out, I'd never expect it to emit control sequences, even if it is awake and doing other things.

**Comment by rschmitt** [comment]
Well, if all they want is the ability to capture ^C, I would imagine that they could just set `isig` (on top of the raw mode that `silent` uses) before shelling out. And capturing ^C like this actually _is_ useful behavior, by the way: if for example I hit `,f` in the wrong directory and kick off a really slow `find` command, I can kill it immediately by hitting ^C. This breaks if I remove the offending `settmode` calls from `mch_delay`.

To your point, _after_ vim has shelled out, it makes no sense to emit further control sequences: if the child process doesn't alter the line discipline then vim can simply set it once, and if the child process _does_ alter the line discipline then vim _must_ not tamper with it until the child terminates. If said process sets `isig` or `cbreak`, well, that's just too damn bad, isn't it?

For what it's worth, I think Neovim is pursuing the real solution here, which is proper terminal emulation. It is conceptually much simpler for Selecta to get a dedicated pseudoterminal and run as an asynchronous process. I haven't figured out exactly how to do this yet, but I was given some clues [here](https://github.com/neovim/neovim/issues/1044#issuecomment-120659196).
