### ISSUE TITLE
Use input directly

### ISSUE THREAD

**Issue by rosshadden** [garybernhardt/selecta#64]
I think it would be quite useful if `selecta` had a bind that use what the user currently has entered, like `Control+Enter` or `Shift+Enter` or something.

This would mean given a list with `abcd` present, if the user types `abc` and hit said bind, `abc` would be passed through as the result even though `abcd` was highlighted.

This would let users select things that are not in the list if applicable to their situation.

**Comment by untitaker** [comment]
I am not sure either ``Ctrl+Enter`` or ``Shift+Enter`` is even [reliably detectable](https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter)?

**Comment by garybernhardt** [comment]
They're not; neither of those keystrokes is detectable on my machine. I thought I'd replied to this thread about that, but apparently not!

This feature would break a contract that Selecta follows implicitly: every keystroke that it understands will be very standard. Enter selects things; ESC and ^C quit; ^P and ^N move through the list; etc. There's no standard key for the behavior we're talking about here, so I'm going to veto it for now. If the standard-keystroke rule ever goes away (which would require a very compelling feature addition), we can revisit this.
