### ISSUE TITLE
Down arrow kills Selecta

### ISSUE THREAD

**Issue by garybernhardt** [garybernhardt/selecta#71]

**Comment by untitaker** [comment]
I honestly thought that was intended behavior, or at least I didn't think much about it.

You mentioned in another issue that binding the arrow-keys is hard to do without curses. Is this still correct, is there even a way to solve this issue?

**Comment by garybernhardt** [comment]
Yeah... it's caused by the newly-added support for ESC. When you hit an arrow key, it sends an escape sequence. Selecta sees the ESC character and aborts, thinking that you hit the escape key.

The normal workaround is to introduce some kind of delay. You see an ESC, and you wait 250 ms or so before assuming that it's an actual press of the ESC key. I think I'm just going to revert the support for ESC. I should've trusted my intuition on that. ;)

**Comment by untitaker** [comment]
What about simply requiring ESC to be hit twice? That'd allow selecta to support arrow keys as well.

**Comment by alexch** [comment]
![vt100](http://upload.wikimedia.org/wikipedia/commons/9/99/DEC_VT100_terminal.jpg)
VT100 4EVR
