### ISSUE TITLE
\t is not properly highlighted

### ISSUE THREAD

**Issue by untitaker** [garybernhardt/selecta#73]
I hesitated long to report this bug, because I think the output looks pretty neat:

![1421167652](https://cloud.githubusercontent.com/assets/837573/5724500/4cf72e1a-9b4c-11e4-9f9e-d98918c5c7cf.png)

**Comment by garybernhardt** [comment]
That seems to just be the behavior of the terminal:
![screen shot 2015-01-13 at 5 36 55 pm](https://cloud.githubusercontent.com/assets/45707/5732669/d43cbdf6-9b4a-11e4-9ebc-f94bd0ededfe.png)

**Comment by untitaker** [comment]
Would you accept a patch that replaces tabs with spaces, just for the UI?

**Comment by garybernhardt** [comment]
That sounds scary. You'd have to compute the next tab stop, which is a function of the previous text. The tab's starting point varies not only based on the number of prior characters, but where the nearest previous tab stop was. And you don't count bytes or codepoints; you count Unicode graphemes, and who knows whether (1) Ruby will do the right thing, especially across versions; and (2) whether the terminal will do the right thing. Like input escape sequences (arrow keys etc.), Unicode in terminals is still sufficiently broken that I don't want to get into that game. Selecta should be as ignorant of Unicode as it can afford to be (which is currently pretty ignorant).

(Opinion time: I think that tabs were a horrible mistake that should be purged from this world, for this reason and others. ;)

**Comment by untitaker** [comment]
Fair enough. I thought about a less correct implementation that would simply do ``s.gsub(/\t/, '    ')``.
