### ISSUE TITLE
Match count label

### ISSUE THREAD

**Issue by gustavnikolaj** [garybernhardt/selecta#78]
I enjoy using selecta for file/buffer opening in vim. But I would like the match count label to be optional. 

Specifically this line: https://github.com/garybernhardt/selecta/blob/8135e7230f3e04d0efde3848b28e240f5dcf2976/selecta#L354 where it outputs the number of matched lines in front of the input.

I have been using it for a while on my laptop where I didn't notice it - I only just saw it as I installed it on my desktop, so I guess it's a new addition.

**Comment by garybernhardt** [comment]
Why?

**Comment by gustavnikolaj** [comment]
I'm sorry if I came off wrong in the original issue, that was not my intention.

Is there any major use case for this feature that I don't see? While I can see that it might have uses, I cannot come up with a practical example my self.

It does not provide any value for the use cases I have, as I'm primarily using it for file selection within vim, and I will just type parts of the filename I want, until it's on top. When the number of matches decrease, it will cause the left side of the prompt to jump and that is a bit disturbing.

**Comment by garybernhardt** [comment]
What if you change the `rjust` to an `ljust`?

**Comment by gustavnikolaj** [comment]
Sorry for the late response.

I tried changing the `rjust` to an `ljust` as you suggested - `rjust` is definitely better. :-) I guess it's not jumping - as the prompt itself doesn't change.

I still feel that the changing number prepended the prompt is disturbing. I generally do not care about the number of matches - I just write until I have the file I need at the top and then move on. So I'd like to be able to turn it off.

If you don't agree, feel free to close this issue. I just wanted to leave the feedback as a happy user of selecta.
