### ISSUE TITLE
--search broken on master

### ISSUE THREAD

**Issue by gshutler** [garybernhardt/selecta#83]
$ echo -e "foo\nbar\nbaz\nquux" | selecta --search ba
    4 > ba
    foo
    bar
    baz
    quux

Typing to alter the search text works as expected, it seems to just be the initial state.

**Comment by gshutler** [comment]
It looks like the [`Search.blank` here](https://github.com/garybernhardt/selecta/blob/123dcff2777d146b3858ec929a85430aa19a67e7/selecta#L59) only results in [trivial matches being recorded on load](https://github.com/garybernhardt/selecta/blob/123dcff2777d146b3858ec929a85430aa19a67e7/selecta#L212).

**Comment by gshutler** [comment]
Not sure how best to alter that behaviour.

**Comment by garybernhardt** [comment]
Fixed, with a test on Search so it won't go unnoticed again. Now I doubly-regret adding that argument!
