### ISSUE TITLE
The way to render menu full-height

### ISSUE THREAD

**Issue by sgtpep** [garybernhardt/selecta#91]
For some unknown reason the height of menu is limited to 20 lines. And there's no way to override this without editing the source. IMHO full-height mode should be default, while limiting height could be available using command line option.

**Comment by rschmitt** [comment]
Full-height mode is only a good default for vim integration. It sucks for the command line, since it blows away a lot of useful context. You can experiment with [heatseeker](https://github.com/rschmitt/heatseeker)'s `--full-screen` option to see if you _really_ want this to be the default.

**Comment by garybernhardt** [comment]
I just added a --height option in 299ca42. You can say `--height full` to run in full screen. The default is still 20 lines, though, for the reason that @rschmitt pointed out.
