### ISSUE TITLE
Prompt left at top of choices after choosing an option

### ISSUE THREAD

**Issue by airblade** [garybernhardt/selecta#98]
An animated gif would provide the clearest explanation but I'm not sure how to make one.  So here's a screenshot of the end result:

![screen shot 2016-02-09 at 10 39 44 am](https://cloud.githubusercontent.com/assets/7265/12913924/79068e5e-cf19-11e5-9f86-16138c09dabe.png)

When I use selecta via my `proj` function, which looks like this:

```
cd $(find ~/code/src -maxdepth 3 -type d | selecta)
```

– and I make a choice, the prompt isn't placed below the choices; it overwrites at the top.

This started happening after I upgraded to 8cb52e7.  I'm not sure what commit I was at before but I hadn't updated for a few months.  I'm using OS X 10.11.3's Terminal.app and Ruby 2.3.0p0.

**Comment by gshutler** [comment]
Seeing similar behaviour. `selecta` appears to move the cursor down a few lines on termination rather than 20 or so as it did before. Therefore if you still have several options visible when you make your selection your cursor ends up in the middle of them rather than below them.

**Comment by gshutler** [comment]
Example against this repo:

```
~/Code/garybernhardt/selecta master
$ ls | selecta
 4 > g
Gemfile
demo.gif
~/Code/garybernhardt/selecta master
$ lecta.gemspec
```

**Comment by garybernhardt** [comment]
This doesn't normally happen on my machine, but I can reproduce it if I remove all environment variables and zsh configuration by doing `env -i zsh -f -d`. With all of my usual configs in place, the cursor ends where it does for both of you, but those extra lines are somehow magically cleared at termination. Fun!

I just pushed e74ee23, which seems to fix this. Can one of you confirm that?

**Comment by garybernhardt** [comment]
Err... that commit has its own bug; let me fix that real quick...

**Comment by garybernhardt** [comment]
OK; I fixed that. The new HEAD is 96df2e9 and definitely works and there will never be bugs again, ever!

**Comment by gshutler** [comment]
Looks good to me from a quick test.

**Comment by airblade** [comment]
Works for me.  Many thanks!

**Comment by airblade** [comment]
I should have mentioned at the start I'm using OS X's system bash, i.e. GNU bash v3.2.57(1)-release.  Sorry!
